# permissions for end users to view timeleaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timeleap-viewer-role
rules:
- apiGroups:
  - timeleap.x-k8s.io
  resources:
  - timeleaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - timeleap.x-k8s.io
  resources:
  - timeleaps/status
  verbs:
  - get
