apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: docker.io/kindest/node:v1.19.1
  kubeadmConfigPatches:
  - |
    # https://kind.sigs.k8s.io/docs/user/ingress/
    # See also: https://pkg.go.dev/k8s.io/kubernetes@v1.19.3/cmd/kubeadm/app/apis/kubeadm/v1beta2
    apiversion: kubeadm.k8s.io/v1beta2
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=false"
    ---
    apiversion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        enable-admission-plugins: noderestriction,mutatingadmissionwebhook,validatingadmissionwebhook
  # extraPortMappings:
  # - containerPort: 5000
  #   hostPort: 5000
  #   listenAddress: 127.0.0.1
  #   protocol: TCP
  # - containerPort: 80
  #   hostPort: 80
  #   listenAddress: 127.0.0.1
  #   protocol: TCP
  # - containerPort: 443
  #   hostPort: 443
  #   listenAddress: 127.0.0.1
  #   protocol: TCP
- role: worker
  image: docker.io/kindest/node:v1.19.1
- role: worker
  image: docker.io/kindest/node:v1.19.1
